import type { LegacyPetSpriteData } from './types'

const p = {
  _: 0, O: 1, o: 2, d: 3, W: 4, P: 5, n: 6, k: 7, f: 8, b: 9,
} as const

export const catSprite: LegacyPetSpriteData = {
  petType: 'cat',
  palette: [
    'transparent', '#2D2D2D', '#F4A623', '#D4891A', '#FFFFFF',
    '#1A1A1A', '#FFB6C1', '#F4A6B2', '#F5F0E8', '#FFD0D0',
  ],
  frames: {
    idle: {
      width: 16, height: 16,
      grid: [
        [p._,p._,p._,p.O, p._,p._,p._,p._,p._,p._,p._,p.O, p._,p._,p._,p._],
        [p._,p._,p.O, p.o, p.O, p._,p._,p._,p._,p.O, p.o, p.O, p._,p._,p._,p._],
        [p._,p._,p.O, p.k, p.o, p.O, p._,p._,p.O, p.o, p.k, p.O, p._,p._,p._,p._],
        [p._,p._,p.O, p.o, p.O, p._,p._,p._,p._,p.O, p.o, p.O, p._,p._,p._,p._],
        [p._,p.O, p.o, p.o, p.o, p.o, p.o, p.o, p.o, p.o, p.o, p.o, p.o, p.O, p._,p._],
        [p._,p.O, p.o, p.W, p.P, p.o, p.o, p.o, p.o, p.W, p.P, p.o, p.o, p.O, p._,p._],
        [p._,p.O, p.o, p.W, p.P, p.o, p.b, p.o, p.b, p.o, p.W, p.P, p.o, p.O, p._,p._],
        [p._,p.O, p.o, p.o, p.o, p.o, p.o, p.n, p.o, p.o, p.o, p.o, p.o, p.O, p._,p._],
        [p._,p.O, p.o, p.o, p.d, p.o, p.o, p.o, p.o, p.d, p.o, p.o, p.o, p.O, p._,p._],
        [p._,p.O, p.o, p.o, p.o, p.o, p.o, p.o, p.o, p.o, p.o, p.o, p.o, p.O, p._,p.o],
        [p._,p.O, p.f, p.f, p.f, p.f, p.f, p.f, p.f, p.f, p.f, p.f, p.f, p.O, p._,p.o],
        [p._,p.O, p.f, p.f, p.f, p.f, p.f, p.f, p.f, p.f, p.f, p.f, p.f, p.O, p.o, p.O],
        [p._,p._,p.O, p.O, p.O, p.O, p.O, p.O, p.O, p.O, p.O, p.O, p.O, p.O, p.o, p._],
        [p._,p._,p._,p.O, p.O, p.O, p.O, p.O, p.O, p.O, p.O, p.O, p.o, p._,p._,p._],
        [p._,p._,p._,p._,p._,p._,p._,p._,p._,p._,p._,p.o, p._,p._,p._,p._],
        [p._,p._,p._,p._,p._,p._,p._,p._,p._,p._,p._,p._,p._,p._,p._,p._],
      ],
    },
    blink: {
      width: 16, height: 16,
      grid: [
        [p._,p._,p._,p.O, p._,p._,p._,p._,p._,p._,p._,p.O, p._,p._,p._,p._],
        [p._,p._,p.O, p.o, p.O, p._,p._,p._,p._,p.O, p.o, p.O, p._,p._,p._,p._],
        [p._,p._,p.O, p.k, p.o, p.O, p._,p._,p.O, p.o, p.k, p.O, p._,p._,p._,p._],
        [p._,p._,p.O, p.o, p.O, p._,p._,p._,p._,p.O, p.o, p.O, p._,p._,p._,p._],
        [p._,p.O, p.o, p.o, p.o, p.o, p.o, p.o, p.o, p.o, p.o, p.o, p.o, p.O, p._,p._],
        [p._,p.O, p.o, p.o, p.o, p.o, p.o, p.o, p.o, p.o, p.o, p.o, p.o, p.O, p._,p._],
        [p._,p.O, p.o, p.O, p.P, p.O, p.b, p.o, p.b, p.O, p.P, p.O, p.o, p.O, p._,p._],
        [p._,p.O, p.o, p.o, p.o, p.o, p.o, p.n, p.o, p.o, p.o, p.o, p.o, p.O, p._,p._],
        [p._,p.O, p.o, p.o, p.d, p.o, p.o, p.o, p.o, p.d, p.o, p.o, p.o, p.O, p._,p._],
        [p._,p.O, p.o, p.o, p.o, p.o, p.o, p.o, p.o, p.o, p.o, p.o, p.o, p.O, p._,p.o],
        [p._,p.O, p.f, p.f, p.f, p.f, p.f, p.f, p.f, p.f, p.f, p.f, p.f, p.O, p._,p.o],
        [p._,p.O, p.f, p.f, p.f, p.f, p.f, p.f, p.f, p.f, p.f, p.f, p.f, p.O, p.o, p.O],
        [p._,p._,p.O, p.O, p.O, p.O, p.O, p.O, p.O, p.O, p.O, p.O, p.O, p.O, p.o, p._],
        [p._,p._,p._,p.O, p.O, p.O, p.O, p.O, p.O, p.O, p.O, p.O, p.o, p._,p._,p._],
        [p._,p._,p._,p._,p._,p._,p._,p._,p._,p._,p._,p.o, p._,p._,p._,p._],
        [p._,p._,p._,p._,p._,p._,p._,p._,p._,p._,p._,p._,p._,p._,p._,p._],
      ],
    },
    happy: {
      width: 16, height: 16,
      grid: [
        [p._,p._,p._,p.O, p._,p._,p._,p._,p._,p._,p._,p.O, p._,p._,p._,p._],
        [p._,p._,p.O, p.o, p.O, p._,p._,p._,p._,p.O, p.o, p.O, p._,p._,p.o, p._],
        [p._,p._,p.O, p.k, p.o, p.O, p._,p._,p.O, p.o, p.k, p.O, p._,p._,p.O, p._],
        [p._,p._,p.O, p.o, p.O, p._,p._,p._,p._,p.O, p.o, p.O, p._,p._,p.o, p._],
        [p._,p.O, p.o, p.o, p.o, p.o, p.o, p.o, p.o, p.o, p.o, p.o, p.o, p.O, p._,p._],
        [p._,p.O, p.o, p.d, p.o, p.o, p.o, p.o, p.o, p.o, p.d, p.o, p.o, p.O, p._,p._],
        [p._,p.O, p.o, p.o, p.o, p.o, p.b, p.o, p.b, p.o, p.o, p.o, p.o, p.O, p._,p._],
        [p._,p.O, p.o, p.o, p.o, p.o, p.o, p.n, p.o, p.o, p.o, p.o, p.o, p.O, p._,p._],
        [p._,p.O, p.o, p.o, p.o, p.o, p.o, p.o, p.o, p.o, p.o, p.o, p.o, p.O, p._,p._],
        [p._,p.O, p.o, p.o, p.o, p.o, p.o, p.o, p.o, p.o, p.o, p.o, p.o, p.O, p._,p.o],
        [p._,p.O, p.f, p.f, p.f, p.f, p.f, p.f, p.f, p.f, p.f, p.f, p.f, p.O, p.o, p.O],
        [p._,p.O, p.f, p.f, p.f, p.f, p.f, p.f, p.f, p.f, p.f, p.f, p.f, p.O, p._,p._],
        [p._,p._,p.O, p.O, p.O, p.O, p.O, p.O, p.O, p.O, p.O, p.O, p.O, p.O, p._,p._],
        [p._,p._,p._,p.O, p.O, p.O, p.O, p.O, p.O, p.O, p.O, p.O, p._,p._,p._,p._],
        [p._,p._,p._,p._,p._,p._,p._,p._,p._,p._,p._,p._,p._,p._,p._,p._],
        [p._,p._,p._,p._,p._,p._,p._,p._,p._,p._,p._,p._,p._,p._,p._,p._],
      ],
    },
    sad: {
      width: 16, height: 16,
      grid: [
        [p._,p._,p._,p._,p._,p._,p._,p._,p._,p._,p._,p._,p._,p._,p._,p._],
        [p._,p._,p._,p.O, p._,p._,p._,p._,p._,p._,p._,p.O, p._,p._,p._,p._],
        [p._,p._,p.O, p.o, p.O, p._,p._,p._,p._,p.O, p.o, p.O, p._,p._,p._,p._],
        [p._,p._,p.O, p.k, p.o, p.O, p._,p._,p.O, p.o, p.k, p.O, p._,p._,p._,p._],
        [p._,p.O, p.o, p.o, p.o, p.o, p.o, p.o, p.o, p.o, p.o, p.o, p.o, p.O, p._,p._],
        [p._,p.O, p.o, p.W, p.P, p.P, p.o, p.o, p.P, p.P, p.W, p.o, p.o, p.O, p._,p._],
        [p._,p.O, p.o, p.o, p.o, p.o, p.o, p.o, p.o, p.o, p.o, p.o, p.o, p.O, p._,p._],
        [p._,p.O, p.o, p.o, p.o, p.o, p.o, p.n, p.o, p.o, p.o, p.o, p.o, p.O, p._,p._],
        [p._,p.O, p.o, p.o, p.d, p.o, p.o, p.o, p.o, p.d, p.o, p.o, p.o, p.O, p._,p._],
        [p._,p.O, p.o, p.o, p.o, p.o, p.o, p.o, p.o, p.o, p.o, p.o, p.o, p.O, p._,p.o],
        [p._,p.O, p.f, p.f, p.f, p.f, p.f, p.f, p.f, p.f, p.f, p.f, p.f, p.O, p._,p.o],
        [p._,p.O, p.f, p.f, p.f, p.f, p.f, p.f, p.f, p.f, p.f, p.f, p.f, p.O, p.o, p.O],
        [p._,p._,p.O, p.O, p.O, p.O, p.O, p.O, p.O, p.O, p.O, p.O, p.O, p.O, p.o, p._],
        [p._,p._,p._,p.O, p.O, p.O, p.O, p.O, p.O, p.O, p.O, p.O, p.o, p._,p._,p._],
        [p._,p._,p._,p._,p._,p._,p._,p._,p._,p._,p._,p.o, p._,p._,p._,p._],
        [p._,p._,p._,p._,p._,p._,p._,p._,p._,p._,p._,p._,p._,p._,p._,p._],
      ],
    },
    sleep: {
      width: 16, height: 16,
      grid: [
        [p._,p._,p._,p._,p._,p._,p._,p._,p._,p._,p._,p._,p._,p._,p._,p._],
        [p._,p._,p._,p._,p._,p._,p._,p._,p._,p._,p._,p._,p._,p._,p._,p._],
        [p._,p._,p._,p._,p._,p._,p._,p._,p._,p._,p._,p._,p._,p._,p._,p._],
        [p._,p._,p._,p._,p._,p._,p._,p._,p._,p._,p._,p._,p._,p._,p._,p._],
        [p._,p._,p._,p._,p._,p._,p.O, p.O, p.O, p.O, p.O, p.O, p._,p._,p._,p._],
        [p._,p._,p._,p._,p._,p.O, p.o, p.o, p.o, p.o, p.o, p.o, p.O, p._,p._,p._],
        [p._,p._,p._,p._,p.O, p.o, p.o, p.o, p.o, p.o, p.o, p.o, p.o, p.O, p._,p._],
        [p._,p._,p._,p.O, p.o, p.o, p.o, p.o, p.o, p.o, p.o, p.o, p.o, p.o, p.O, p._],
        [p._,p._,p._,p.O, p.o, p.O, p.P, p.o, p.o, p.O, p.P, p.o, p.o, p.o, p.O, p._],
        [p._,p._,p._,p.O, p.o, p.o, p.o, p.o, p.n, p.o, p.o, p.o, p.o, p.o, p.O, p._],
        [p._,p._,p._,p.O, p.o, p.o, p.o, p.o, p.o, p.o, p.o, p.o, p.o, p.o, p.O, p._],
        [p._,p._,p._,p._,p.O, p.f, p.f, p.f, p.f, p.f, p.f, p.f, p.f, p.O, p._,p._],
        [p._,p._,p._,p._,p._,p.O, p.O, p.O, p.O, p.O, p.O, p.O, p.O, p._,p._,p._],
        [p._,p._,p._,p._,p._,p._,p._,p._,p._,p._,p._,p._,p._,p._,p._,p._],
        [p._,p._,p._,p._,p._,p._,p._,p._,p._,p._,p._,p._,p._,p._,p._,p._],
        [p._,p._,p._,p._,p._,p._,p._,p._,p._,p._,p._,p._,p._,p._,p._,p._],
      ],
    },
    special: {
      width: 16, height: 16,
      grid: [
        [p._,p._,p._,p.O, p._,p._,p._,p._,p._,p._,p._,p.O, p._,p._,p._,p._],
        [p._,p._,p.O, p.o, p.O, p._,p._,p._,p._,p.O, p.o, p.O, p._,p._,p.o, p._],
        [p._,p._,p.O, p.k, p.o, p.O, p._,p._,p.O, p.o, p.k, p.O, p._,p._,p.O, p._],
        [p._,p._,p.O, p.o, p.O, p._,p._,p._,p._,p.O, p.o, p.O, p._,p.o, p.o, p._],
        [p._,p.O, p.o, p.o, p.o, p.o, p.o, p.o, p.o, p.o, p.o, p.o, p.o, p.O, p.O, p._],
        [p._,p.O, p.o, p.W, p.P, p.o, p.o, p.o, p.o, p.W, p.P, p.o, p.o, p.O, p.o, p._],
        [p._,p.O, p.o, p.W, p.P, p.o, p.b, p.o, p.b, p.o, p.o, p.o, p.o, p.O, p._,p._],
        [p._,p.O, p.o, p.o, p.o, p.o, p.o, p.n, p.o, p.o, p.o, p.o, p.o, p.O, p.O, p._],
        [p._,p.O, p.o, p.o, p.d, p.o, p.o, p.o, p.o, p.d, p.o, p.o, p.o, p.O, p.o, p._],
        [p._,p.O, p.o, p.o, p.o, p.o, p.o, p.o, p.o, p.o, p.o, p.o, p.o, p.O, p.o, p._],
        [p._,p.O, p.f, p.f, p.f, p.f, p.f, p.f, p.f, p.f, p.f, p.f, p.f, p.O, p.O, p._],
        [p._,p.O, p.f, p.f, p.f, p.f, p.f, p.f, p.f, p.f, p.f, p.f, p.f, p.O, p._,p._],
        [p._,p._,p.O, p.O, p.O, p.O, p.O, p.O, p.O, p.O, p.O, p.O, p.O, p.O, p._,p._],
        [p._,p._,p._,p.O, p.O, p.O, p.O, p.O, p.O, p.O, p.O, p.O, p._,p._,p._,p._],
        [p._,p._,p._,p._,p._,p._,p._,p._,p._,p._,p._,p._,p._,p._,p._,p._],
        [p._,p._,p._,p._,p._,p._,p._,p._,p._,p._,p._,p._,p._,p._,p._,p._],
      ],
    },
  },
}
